config/routes.rb
SIBMt::Application.routes.draw do
  

  root :to => 'profiles#show', :id => '1'


  match '/cmo' => 'profiles#show', :id => '1' 
  match '/ss'  => 'profiles#show', :id => '2' 
  match '/ca'  => 'profiles#show', :id => '3' 

  resources :profiles,           :only => [:show, :edit, :update] do
    resources :platform_stories,  :only => [:new, :create, :edit, :update]
    resources :market_data,       :only => [:edit, :update]
    resources :case_studies,      :only => [:new, :create, :edit, :update]
  end

  resources :faqs,              :only => [:new, :create, :edit, :update, :destroy]
  resources :faq_answers,       :only => [:destroy]
  
  
  resources :units,             :only => [:index, :show, :new, :create, :destroy]
  resources :misc_resources,    :only => [:new, :create, :destroy]

end

app/models/case_study.rb
class CaseStudy < ActiveRecord::Base
  attr_accessible :title, :description, :img_url

  belongs_to :profile

  validates :title, :description, :img_url, :presence => true
  
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :question, :faq_answers_attributes

  validates :question, :presence => true

  has_many :faq_answers, :inverse_of => :faq

  accepts_nested_attributes_for :faq_answers, :allow_destroy => true,
    :reject_if => proc { |answers| answers.all? { |k, v| v.blank? } }

end

app/models/faq_answer.rb
class FaqAnswer < ActiveRecord::Base
  attr_accessible :answer, :faq_id

  belongs_to :faq, :inverse_of => :faq_answers

end

app/models/market_datum.rb
class MarketDatum < ActiveRecord::Base
  attr_accessible :title, :description, :profile_id

  belongs_to :profile, :inverse_of => :market_data

  validates :title, :description, :profile_id, :presence => true
end

app/models/misc_resource.rb
class MiscResource < ActiveRecord::Base
  attr_accessible :description, :link_url

  validates :description, :link_url, :presence => true
end

app/models/platform_story.rb
class PlatformStory < ActiveRecord::Base
  attr_accessible :title, :description , :profile_id

  belongs_to :profile, :inverse_of => :platform_stories

  validates :title, :description, :profile_id, :presence => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :name, :description, :title, :img_url

  has_many :market_data
  has_many :platform_stories
  has_many :case_studies

  # scope :for_cmo, where(:cmo => true) 
  # scope :for_ss, where(:social_strategist => true)
  # scope :for_ca, where(:creative_agency => true)

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :description, :unit_type, 
        :long_description, :image_path, :thumbnail_path

  validates :name, :description, :unit_type, :image_path, :thumbnail_path, :presence => true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

end

app/controllers/faq_answers_controller.rb
class FaqAnswersController < ApplicationController

  def destroy
    @faq_answer = FaqAnswer.find(params[:id])
    @faq_answer.destroy
    flash[:notice] = "Thank you for cleaning up the knowledge database"
    redirect_to root_path
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  # def index
  #   @faqs = Faq.all
  # end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(params[:faq])

    if @faq.save
      flash[:notice] = "Thank you for adding to the knowledge database"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])

    if @faq.update_attributes(params[:faq])
      flash[:notice] = "Thank you for updating our knowledge database"
      redirect_to root_path
    else
      render 'edit'
    end
  end


  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    flash[:notice] = "You have deleted a question"
    redirect_to root_path
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = Profile.find(params[:id])
    @units = Unit.all
    @faqs = Faq.all
    @misc_resources = MiscResource.all
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Thank you for updating the profile"
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController


  def index
    @units = Unit.all
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(params[:unit])

    if @unit.save 
      flash[:notice] = "You have successfully created a new unit"
      redirect_to units_path
    else
      render 'new'
    end

  end

  def show
    @unit = Unit.find(params[:id])
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    flash[:notice] = "You have successfully deleted a unit"
    redirect_to units_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(text).html_safe
  end

  def errors_for(object)
    if object.errors.any?
      render 'shared/errors', :object => object
    end
  end

end

app/helpers/buttons_helper.rb
module ButtonsHelper
 
  def edit_btn(text="")
    return "<i class='icon-edit'>#{text}</i>".html_safe
  end

  def add_btn(text="")
    return "<i class='icon-plus'>#{text}</i>".html_safe
  end

  def back_btn(text="")
    return "<i class='icon-backward'>#{text}</i>".html_safe
  end

  def delete_btn(text="")
    return "<i class='icon-remove'>#{text}</i>".html_safe
  end

end

app/helpers/case_studies_helper.rb
module CaseStudiesHelper
end

app/helpers/faq_answers_helper.rb
module FaqAnswersHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/market_data_helper.rb
module MarketDataHelper
end

app/helpers/misc_resources_helper.rb
module MiscResourcesHelper
end

app/helpers/platform_stories_helper.rb
module PlatformStoriesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/faqs/_form.html.erb
  <div id="faqs-form">
  <% @faq.faq_answers.build %>
    <%= form_for @faq do |faq_form| %>
      <table class="new-faq-form">

        <tr>
          <%= faq_form.label :question %>
          <%= faq_form.text_field :question %>
        </tr>

        <%= faq_form.fields_for :faq_answers do |faq_answers_form| %>
        <tr>
          <%= faq_answers_form.label :answer %>
          <%= faq_answers_form.text_field :answer %>
        </tr>
        <% end %>

      </table>    
      </br>
      <div class='submit-btn'>
          <%= faq_form.submit "Submit", :class => 'btn' %>
      </div>
    <% end %>
   
  </div><!-- end faqs form -->

app/views/faqs/edit.html.erb
<div id="faqs-container" class="container">
<%= link_to back_btn, :back, :class => 'btn' %>
  <h2>Edit or add to the knowledge database</h2>

  <%= render "form" %>

</div> <!-- end faqs container -->

app/views/faqs/index.html.erb
<h3>FAQ</h3>
<ul>
<% @faqs.each do |faq| %>
  <li><%= faq.question %></li>
  <li><%= faq.faq_answers %></li>
<% end %>
</ul>
<p><%= link_to "Add question", new_faq_path, :class => 'btn' %></p>

app/views/faqs/new.html.erb
<div id="faqs-container" class="container">

  <h2>Add to the knowledge database</h2>

  <div id="faqs-form">

    <%= form_for @faq do |faq_form| %>
      <table class="new-faq-form">

        <tr>
          <%= faq_form.label :question %>
          <%= faq_form.text_field :question %>
        </tr>

        <%= faq_form.fields_for :faq_answers do |faq_answers_form| %>
        <tr>
          <%= faq_answers_form.label :answer %>
          <%= faq_answers_form.text_field :answer %>
        </tr>
        
        <% end %>
      </table>    
      </br>
      <div class='submit-btn'>
          <%= faq_form.submit "Submit questions", :class => 'btn' %>
      </div>
      <% end %>

    </div>
</div>

app/views/profiles/_case_study.html.erb
<div class="case-study-container">
  <div class="row">
  <% @profile.case_studies.each do |case_study| %>
  
  <%= link_to edit_btn("edit"), edit_profile_case_study_path(@profile, case_study), :class => 'btn btn-small edit-btn pull-right' %>

    <div class="span5">
      <h4 class="case-study-title"><%= case_study.title %></h4>
        <div class="case-study-info">
          <%= markdown(case_study.description) %>
        </div><!-- end for case study info -->
    </div>


        
    <div class="span4">
      <a href="#case-study-modal" data-toggle="modal"><%= image_tag case_study.img_url, :class => 'case-study-img' %></a>
    </div><!-- end case study image -->
    

      <div id="case-study-modal" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <%= image_tag case_study.img_url %>
        </div>
      </div><!-- end case study modal -->
  <% end %>

  </div><!-- end row -->

  <%= link_to add_btn(" Add case study"), new_profile_case_study_path(@profile), :class => 'btn btn-small add-btn' %>


</div><!-- end case study container -->

app/views/profiles/_description.html.erb
<div class="description-container">
  
  
  <%= link_to edit_btn("edit"), edit_profile_path(@profile), :class => 'btn btn-small edit-btn' %>

  <div class="description-img">
    <%= image_tag @profile.img_url, :class => 'toast-person-img' %>
  </div>


  <div class="description-text">
    <h4 class="profile-title"><%= @profile.title %></h4>
      <div class="profile-info">
      <%= markdown(@profile.description) %>
      </div><!-- end list profile info -->
  </div><!-- end list profile description -->
  

  
</div>

app/views/profiles/_faqs.html.erb
<div class="faqs-container">

  <ol>
  <% @faqs.each do |faq| %>
    <a data-toggle="collapse" data-parent="#profile-name" href="#answer-<%= faq.id %>">
      <li class="question"><%= faq.question %> <%= link_to edit_btn, edit_faq_path(faq.id) %></li>
    </a> 
      <ul id="answer-<%= faq.id %>" class="collapse">
        <% faq.faq_answers.each do |faq_answer| %>
        <li class="answer"><%= faq_answer.answer %> <%= link_to delete_btn, faq_answer_path(faq_answer.id), :method=>:delete, :class=>:destroy,:confirm=>"Are you sure?"%></li> 
        <% end %>
      </ul>
  <% end %>
  </ol>
  <p><%= link_to add_btn(" Add question"), new_faq_path, :class => 'btn btn-small add-btn' %></p>

</div>

app/views/profiles/_market_data.html.erb
<div class="market-data-container">

  <div>
    <% @profile.market_data.each do |market_datum| %>
    <%= link_to edit_btn("edit"), edit_profile_market_datum_path(@profile, market_datum), :class => 'btn btn-small edit-btn' %>
    <h4 class="market-data-title"><%= market_datum.title %></h4>
      <div class="market-data-info">
      <%= markdown(market_datum.description) %>
      </div><!-- end list for market data -->
    <% end %>
  </div>


</div>

app/views/profiles/_misc_resources.html.erb
<div class="misc-resources-container">
  <ul>
  <% @misc_resources.each do |misc| %>
    
      <li><%= link_to 'Go to', "http://#{misc.link_url}", :target=> "_blank" %> <%= misc.description %> <%= link_to delete_btn, misc_resource_path(misc), :method => :delete, :confirm => 'Are you sure?' %></li>

  <% end %>
  </ul>
  <p><%= link_to add_btn(" Add resource"), new_misc_resource_path, :class => 'btn btn-small add-btn' %></p>
</div>

app/views/profiles/_platform_story.html.erb
<div class="platform-story-container">
  <div>
    <% @profile.platform_stories.each do |platform_story| %>
     <%= link_to edit_btn("edit"), edit_profile_platform_story_path(@profile, platform_story), :class => 'btn btn-small edit-btn' %>
    <h4 class="platform-story-title"><%= platform_story.title %></h4>
      <div class="platform-story-info">
      <%= markdown(platform_story.description) %>
      </div><!-- end platform story info-->
    <% end %>
  </div><!-- end list of platform stories -->

<%= link_to add_btn(" Add platform story"), new_profile_platform_story_path(@profile), :class => 'btn btn-small new-btn' %>

</div>

app/views/profiles/edit.html.erb
<%= link_to "<i class='icon-backward'></i>".html_safe, :back, :class => 'btn back-btn' %>
<div id="profiles-container" class="container">


  <h2>Edit the <%= @profile.name %> profile</h2>


    <div id="profiles-form">

        <%= form_for @profile do |f| %>
        <table class="edit-profile-form">

          <tr>
            <%= f.label :title, "Persona's Title" %>
            <%= f.text_field :title %>
          </tr>

          <tr>
            <%= f.label :description %> 
            <%= render "shared/markdown_notice" %> 
            <%= f.text_area :description %>
          </tr>
          <tr>
            <%= f.label :img_url, "Image filename" %>
            <%= f.text_field :img_url %>
          </tr>

        </table>    
        </br>
        <div class='submit-btn'>
            <%= f.submit :class => 'btn'%>
        </div>
        <% end %>

    </div>
    
    <%= render "shared/markdown_guide" %>
    

</div> <!-- end profiles container -->

app/views/profiles/index.html.erb
<h1>Welcome to the App</h1>

<div id="home-btns">
  
  <% @profiles.each do |p| %>
  <div><%= link_to p.name, profile_path(p.id), :class => 'btn btn-large btn-block' %></div></br>
  <% end %>



</div>

app/views/profiles/show.html.erb
<div id="main-page-container" class="container">


  <h1 id="profile-name"> -- <%= @profile.name %> -- </h1>

  <a data-toggle="collapse" data-parent="#profile-name" href="#profile-desc">
    <h2 class="main-section">Profile </h2>  
  </a>
  <div id="profile-desc" class="collapse in info-drop-down">
    <%= render "description" %>
  </div>  <!-- end profile description-->



  <a data-toggle="collapse" data-parent="#profile-name" href="#market-data">
    <h2 class="main-section">Market Data</h2>
  </a>
  <div id="market-data" class="collapse in info-drop-down">
    <%= render "market_data" %>
  </div>  <!-- end market data-->


  <a data-toggle="collapse" data-parent="#profile-name" href="#platform-story">
    <h2 class="main-section">Platform Story</h2>
  </a>
  <div id="platform-story" class="collapse in info-drop-down">
    <%= render "platform_story" %>
  </div>  <!-- end platform story-->


  <a data-toggle="collapse" data-parent="#profile-name" href="#case-study">
    <h2 class="main-section">Case Study</h2>
  </a>
  <div id="case-study" class="collapse in info-drop-down">
    <%= render "case_study" %>
  </div>  <!-- end case study -->

  <a data-toggle="collapse" data-parent="#profile-name" href="#faqs">
  <h2 class="main-section">Frequently Asked Questions</h2>
  </a>
  <div id="faqs" class="collapse in info-drop-down">
    <%= render "faqs" %>
  </div>  <!-- end faqs -->

  <a data-toggle="collapse" data-parent="#profile-name" href="#misc-resources">
  <h2 class="main-section">Miscellaneous Resources</h2>
  </a>
  <div id="misc-resources" class="collapse in info-drop-down">
    <%= render "misc_resources"%>
  </div>  <!-- end misc-resources -->

  <a data-toggle="collapse" data-parent="#profile-name" href="#units-table">
  <h2 class="main-section">Units</h2>
  </a>
  <div id="units-table" class="collapse in info-drop-down">
    <ul>
      <%= render 'shared/table' %>
    </ul>
  </div>  <!-- end units-table -->  


</div><!-- end main page container -->  

app/views/units/index.html.erb
<h2>Welcome to the Units page</h2>

<%= render 'shared/table' %>

<%= link_to 'Create New Unit', new_unit_path, :class => 'btn'%>

app/views/units/new.html.erb
<div id="units-container" class="container">
<%= link_to back_btn, :back, :class=> 'btn' %>
  <h2>Create a new unit below</h2>

  <div id="units-form">

      <%= form_for @unit do |f| %>
      <table class="new-unit-form">

        <tr>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </tr>
        <tr>
          <%= f.label :description %>
          <%= f.text_field :description %>
        </tr>

        <tr>
          <%= f.label :long_description %>
          <%= f.text_area :long_description %>
        </tr>

        <tr>
          <%= f.label :unit_type %>
          <%= f.text_field :unit_type %>
        </tr>

        <tr>
          <%= f.label :image_path %>
          <%= f.text_field :image_path %>
        </tr>
        
        <tr>
          <%= f.label :thumbnail_path %>
          <%= f.text_field :thumbnail_path %>
        </tr>

      </table>    
      </br>
      <div class='submit-btn'>
          <%= f.submit :class => 'btn'%>
      </div>
      <% end %>

    </div>
</div>

app/views/units/show.html.erb
<div id="unit-img">
  <%= image_tag "#{@unit.image_path}", :class => 'pull-left' %>
</div>

<table id="units-table" class="table table-hover">
  <tr>
    <th>Name</th><br/>
    <td><%= @unit.name %></td>
  </tr>
  <tr>
    <th>Type</th><br/>
    <td><%= @unit.unit_type %></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= @unit.long_description %></td>
  </tr>
  

</table>

<%= link_to 'New Unit', new_unit_path, :class => 'btn' %> <br />

<%= link_to 'Back', :back %>