config/routes.rb
SIBMt::Application.routes.draw do
  

  root :to => 'profiles#show', :id => '1'


  match '/cmo' => 'profiles#show', :id => '1' 
  match '/ss'  => 'profiles#show', :id => '2' 
  match '/ca'  => 'profiles#show', :id => '3' 

  resources :profiles,           :only => [:show, :edit, :update] do
    resources :platform_stories,  :only => [:new, :create, :edit, :update]
    resources :market_data,       :only => [:edit, :update]
    resources :case_studies,      :only => [:new, :create, :edit, :update]
  end

  resources :faqs,              :only => [:new, :create, :edit, :update, :destroy]
  resources :faq_answers,       :only => [:destroy]
  
  
  resources :units,             :only => [:index, :show, :new, :create, :destroy]
  resources :misc_resources,    :only => [:new, :create, :destroy]

end

app/models/case_study.rb
class CaseStudy < ActiveRecord::Base
  attr_accessible :title, :description, :img_url

  belongs_to :profile

  validates :title, :description, :img_url, :presence => true
  
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :question, :faq_answers_attributes

  validates :question, :presence => true

  has_many :faq_answers, :inverse_of => :faq

  accepts_nested_attributes_for :faq_answers, :allow_destroy => true,
    :reject_if => proc { |answers| answers.all? { |k, v| v.blank? } }

end

app/models/faq_answer.rb
class FaqAnswer < ActiveRecord::Base
  attr_accessible :answer, :faq_id

  belongs_to :faq, :inverse_of => :faq_answers

end

app/models/market_datum.rb
class MarketDatum < ActiveRecord::Base
  attr_accessible :title, :description, :profile_id

  belongs_to :profile, :inverse_of => :market_data

  validates :title, :description, :profile_id, :presence => true
end

app/models/misc_resource.rb
class MiscResource < ActiveRecord::Base
  attr_accessible :description, :link_url

  validates :description, :link_url, :presence => true
end

app/models/platform_story.rb
class PlatformStory < ActiveRecord::Base
  attr_accessible :title, :description , :profile_id

  belongs_to :profile, :inverse_of => :platform_stories

  validates :title, :description, :profile_id, :presence => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :name, :description, :title, :img_url

  has_many :market_data
  has_many :platform_stories
  has_many :case_studies

  # scope :for_cmo, where(:cmo => true) 
  # scope :for_ss, where(:social_strategist => true)
  # scope :for_ca, where(:creative_agency => true)

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  attr_accessible :name, :description, :unit_type, 
        :long_description, :image_path, :thumbnail_path

  validates :name, :description, :unit_type, :image_path, :thumbnail_path, :presence => true 
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  # def index
  #   @faqs = Faq.all
  # end

  def new
    @faq = Faq.new
  end

  def create
    @faq = Faq.new(params[:faq])

    if @faq.save
      flash[:notice] = "Thank you for adding to the knowledge database"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @faq = Faq.find(params[:id])
  end

  def update
    @faq = Faq.find(params[:id])

    if @faq.update_attributes(params[:faq])
      flash[:notice] = "Thank you for updating our knowledge database"
      redirect_to root_path
    else
      render 'edit'
    end
  end


  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy
    flash[:notice] = "You have deleted a question"
    redirect_to root_path
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = Profile.find(params[:id])
    @units = Unit.all
    @faqs = Faq.all
    @misc_resources = MiscResource.all
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update_attributes(params[:profile])
      flash[:notice] = "Thank you for updating the profile"
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController


  def index
    @units = Unit.all
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(params[:unit])

    if @unit.save 
      flash[:notice] = "You have successfully created a new unit"
      redirect_to units_path
    else
      render 'new'
    end

  end

  def show
    @unit = Unit.find(params[:id])
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    flash[:notice] = "You have successfully deleted a unit"
    redirect_to units_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(text).html_safe
  end

  def errors_for(object)
    if object.errors.any?
      render 'shared/errors', :object => object
    end
  end

end

app/helpers/buttons_helper.rb
module ButtonsHelper
 
  def edit_btn(text="")
    return "<i class='icon-edit'>#{text}</i>".html_safe
  end

  def add_btn(text="")
    return "<i class='icon-plus'>#{text}</i>".html_safe
  end

  def back_btn(text="")
    return "<i class='icon-backward'>#{text}</i>".html_safe
  end

  def delete_btn(text="")
    return "<i class='icon-remove'>#{text}</i>".html_safe
  end

end

app/helpers/case_studies_helper.rb
module CaseStudiesHelper
end

app/helpers/faq_answers_helper.rb
module FaqAnswersHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/market_data_helper.rb
module MarketDataHelper
end

app/helpers/misc_resources_helper.rb
module MiscResourcesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SIB MT" %></title>
    <%= csrf_meta_tags %>
  

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    
    <%= stylesheet_link_tag "application", :media => "all" %>


    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif:400,700,400italic,700italic" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/cmo">
            <%= image_tag "mt_logo.png" %>
          </a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "CMO", '/cmo'  %></li>
              <li><%= link_to "Social Strategist", '/ss'  %></li>
              <li><%= link_to "Creative Agency", '/ca'  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
          
            <%= bootstrap_flash %>
            <%= yield %>


    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SIB MT" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>


    <div id="home-main-container" class="container">
          
            <%= bootstrap_flash %>
            <%= yield %>


    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_errors.html.erb
  

  <div id="errorExplanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited
        this <%= object.title %> from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    </ul>
    <% end %>
  </div>

app/views/shared/_markdown_guide.html.erb
<div id="markdown-guide-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelleby="markdown-guide-modalLabel" aria-hidden="true">
  <!-- <div class="markdown-guide-container"> -->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Markdown syntax</h3>
    </div> <!-- end modal header -->
    
    <div class="modal-body"> 
      <p>Markdown is a markup language. Following these rules will allow you to write your documents semantically. For a more detailed guide please go to <%= link_to "Wikipedia's Markdown article", "http://en.wikipedia.org/wiki/Markdown", :target => "_blank" %>.</p>

      <section>
        <h4 class="markdown-guide-header">Headers</h4>
          <p>Headers are marked by a <code>#</code> symbol.</p>
          <pre>
            # This will output a first-level header  
            #### This will output a fourth-level header
          </pre>
      </section>
      <!-- end markdown headers -->

      <section>
        <h4 class="markdown-guide-header">Paragraphs</h4>
          <p>Paragraphs are simply lines of text.</p>
          <pre>
            This will output a paragraph with one sentence. 
          </pre>
      </section>
      <!-- end markdown paragraphs -->

      <section>
        <h4 class="markdown-guide-header">Lists</h4>
          <p>Lists are marked by <code>*</code>, <code>+</code>, or <code>-</code> for unordered list, and <code>1.</code>,<code>2.</code><code>3.</code>, etc. for ordered lists</p>
          <pre>
              * This will output a list item.
                  * This will be a subitem (indent with 4 spaces)
              * This will be the second list item 
              1. This will output a numbered list item 
              2. This will be the second numbered list item
          </pre>
        </section>
      <!-- end markdown lists -->

      
      <section>
        <h4 class="markdown-guide-header">Emphasized text</h4>
          <p>Emphasis is added by <code>*text*</code> for italics and <code>**text**</code> for bold font</p>
      </section>

      <!-- end markdown Emphasized text -->


      <section>
        <h4 class="markdown-guide-header">Blockquotes</h4>
          <p>Block quotes are marked by a <code> > </code> symbol</p>
          <pre>
            > This will output a block quote. Include one per paragraph. 
          </pre>
      </section>
      <!-- end markdown blockquotes -->

      <section>
        <h4 class="markdown-guide-header">External links</h4>
         <p>Links are marked as <code>[link text](link.address.here)</code>. For example:</p>
         <pre>
           [Visit Moontoast.com](http://www.moontoast.com)
         </pre>
      </section>
      <!-- end markdown external links -->

    </div><!-- end modal body -->
  
  <!-- </div>end markdown guide container -->
</div><!-- end modal -->

app/views/shared/_markdown_notice.html.erb
<div id='markdown-notice'>To write a description please follow <a href='#markdown-guide-modal' class='markdown-explanation-line' data-toggle='modal'>markdown syntax</a> to format your content correctly. 
</div>

app/views/shared/_table.html.erb
<div id="table-name"></div>
<table class="table table-striped">
  <tr>
    <th class="hidden-phone">Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Type</th>
    <!-- <th>Delete</th> -->
  </tr>
  <% @units.each do |unit| %>
  <tr>
    <td class=" hidden-phone"><a href="#unit-image-modal-<%= unit.name.downcase.tr(' ', '_') %>" data-toggle="modal"><%= image_tag unit.thumbnail_path, :class => 'unit-thumbnail' %></a></td>
    
    <td><%= unit.name %><br />
      <a href="#unit-image-modal-<%= unit.name.downcase.tr(' ', '_') %>" data-toggle="modal"><%= image_tag unit.thumbnail_path, :class => 'unit-thumbnail visible-phone' %></a></td>
    <td><%= unit.description %></td>
    <td><%= unit.unit_type %></td>
    <!-- <td><%#= link_to 'Delete', unit_path(unit), :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>

  <div id="unit-image-modal-<%= unit.name.downcase.tr(' ', '_') %>" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3><%= unit.name %> | <%= unit.unit_type %></h3>
    </div>
    <div class="modal-body">
          <p><%= unit.long_description %></p>
          <%= image_tag unit.image_path, :class => 'unit-image'%>
    </div><!-- modal body end -->
  </div>

  

  <% end %>
</table>
<p><%= link_to add_btn(' Create New Unit'), new_unit_path, :class => 'btn btn-small add-btn'%></p>


  